-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
  FROM (SELECT AO.DATETIME - AI.DATETIME AS D,
               AI.ANIMAL_ID, AI.NAME
          FROM ANIMAL_OUTS AO, ANIMAL_INS AI
         WHERE AO.ANIMAL_ID = AI.ANIMAL_ID
         ORDER BY D DESC)
 WHERE ROWNUM < 3