-- 코드를 입력하세요
-- SELECT SEX_UPON_INTAKE
--   FROM ANIMAL_INS
--  WHERE SEX_UPON_INTAKE LIKE 'Intact%'

SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
  FROM (SELECT ANIMAL_ID, SEX_UPON_INTAKE
          FROM ANIMAL_INS
         WHERE SEX_UPON_INTAKE LIKE '%Intact%') AI JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
 WHERE SEX_UPON_OUTCOME NOT LIKE '%Intact%'
 ORDER BY AO.ANIMAL_ID