-- 코드를 입력하세요
SELECT B.HOUR, COUNT(A.HOUR) AS COUNT
  FROM (SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR
          FROM ANIMAL_OUTS) A ,
       (SELECT LEVEL-1 HOUR
          FROM DUAL 
       CONNECT BY LEVEL <= 24) B
 WHERE B.HOUR = A.HOUR(+)
 GROUP BY B.HOUR
 ORDER BY B.HOUR
       
