-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(B.AMOUNT * A.PRICE) TOTAL_SALES
  FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 WHERE TO_CHAR(B.PRODUCE_DATE, 'YYYYMM') = '202205'
 GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID