-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.NAME
  FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
 WHERE AI.DATETIME > AO.DATETIME
 ORDER BY AI.DATETIME
 
--  SELECT A.ANIMAL_ID, A.NAME
-- FROM ANIMAL_INS A, ANIMAL_OUTS B
-- WHERE A.ANIMAL_ID=B.ANIMAL_ID
--     AND A.DATETIME>B.DATETIME
-- ORDER BY A.DATETIME;
