-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT B.USER_ID) AS USERS
  FROM USER_INFO A , (SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR, 
                      TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH,
                      USER_ID
                      FROM ONLINE_SALE ) B
 WHERE GENDER IS NOT NULL
   AND A.USER_ID = B.USER_ID
 GROUP BY YEAR, MONTH, GENDER
 ORDER BY YEAR, MONTH, GENDER
